### ISSUE TITLE
Using data from "whotracks.me"

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#10]
I don't know if it's usable but take a look:
https://whotracks.me/blog/generating_adblocker_filters.html

**Comment by Kees1958** [comment]
That is very interesting. This makes the real life data of Cliqz used in Ghostery available for general use.

**Comment by Kees1958** [comment]
Added some trackers, let's monitor website breakage

**Comment by beerisgood** [comment]
I also use your list in Microsoft (Chromium-)Edge native Tracking protection with this trick:
https://malwaretips.com/threads/edge-tracking-protection-tweak.103454/

Until now I manually add your domains to that file but maybe we can provide a compatible list?
The format is:

> Domain.tld/

**Comment by Kees1958** [comment]
Done, please take it from here 

https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/BeerIsGood_Edge_blocklist

**Comment by beerisgood** [comment]
unfortunately this method is reset with every Edge major update

i will continue to maintain the list, but unfortunately it is not as effective as I thought

i add also a info about that in new commit:
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/d24814a5efdd2e379e1fb6b1288c212fdd53a2bc
