### ISSUE TITLE
Consider removing unpkg.com

### ISSUE THREAD

**Issue by vtvksmy** [Kees1958/W3C_annual_most_used_survey_blocklist#12]
Blocking unpkg.com breaks the functionality of many sites, for example chromestatus.com.

Tested using the Edge Blocklist.

**Comment by vtvksmy** [comment]
Also consider removing stackpathcdn.com. It blocks images here: https://www.wikigain.com/fix-macos-slow-performance-macos-big-sur/

**Comment by beerisgood** [comment]
> Also consider removing stackpathcdn.com. It blocks images here: https://www.wikigain.com/fix-macos-slow-performance-macos-big-sur/

i have opened an own issue for this: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/13

**Comment by Kees1958** [comment]
@beerisgood feel free to update the list, you should have full rights to do so
