### ISSUE TITLE
consider removing stackpathcdn.com

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#13]
Also consider removing stackpathcdn.com. It blocks images here: https://www.wikigain.com/fix-macos-slow-performance-macos-big-sur/

_Originally posted by @vtvksmy in https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/12#issuecomment-727046155_

**Comment by Kees1958** [comment]
@beerisgood feel free to update the list, you should have full rights to do so
