### ISSUE TITLE
Consider removing ampproject.org

### ISSUE THREAD

**Issue by vtvksmy** [Kees1958/W3C_annual_most_used_survey_blocklist#15]
Blocking ampproject.org may break sites when they rely on AMP for functionality.
Example where images are blocked: https://g1.globo.com/df/distrito-federal/noticia/2020/11/28/brasilia-sedia-concurso-de-beleza-miss-supranational-brasil-2020-conheca-candidatas.ghtml

**Comment by beerisgood** [comment]
I personally see this as feature as AMP is Google stuff and should be avoided if possible.

**Comment by Kees1958** [comment]
Removed ampproject.org (sorry Beerisgood your comment crossed my update)

**Comment by vtvksmy** [comment]
In the example above it is blocking the pictures of the beauty pageant candidates from the news article. Better Blocker does not block all content from this domain as it may break site functionality (https://better.fyi/trackers/ampproject.org/).

**Comment by Kees1958** [comment]
changed to  ||ampproject.org$cookie,third-party

**Comment by Kees1958** [comment]
@vtvksmy @beerisgood please use [https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/EU%20US%20most%20commen%20ads%20%26%20trackers%20Edge%20format](url)
