### ISSUE TITLE
Consider removing typekit.net

### ISSUE THREAD

**Issue by vtvksmy** [Kees1958/W3C_annual_most_used_survey_blocklist#16]
Typekit is a font service. Consider removing from Edge Blocklist.
https://better.fyi/trackers/typekit.net/

**Comment by beerisgood** [comment]
Only "p.typekit.net" is in Edge list.
Did you mean that ?

**Comment by Kees1958** [comment]
changed to  ||p.typekit.net$cookie,third-party 

@vtvksmy thanks for opening issue, could you check whether blocking cookie (AdGuard syntax) only solves this problem?

AdBlockers incapable of blocking cookies will probrably ignore this line, so I hope it does not provide problems

**Comment by vtvksmy** [comment]
@beerisgood yes that one.

**Comment by vtvksmy** [comment]
It is possible to block only _storage access_ on Edge instead of blocking both _storage access_ and _resource loads_. To do so would require the user to manually add the domain to the _Content_ file.

It would be too cumbersome having a separate list solely for this _Content_ file and having to update it along with the _Other_ file. Therefore it is best to just remove problematic domains like this one from the Edge Blocklist altogether.
