### ISSUE TITLE
Consider removing cloudinary.com

### ISSUE THREAD

**Issue by vtvksmy** [Kees1958/W3C_annual_most_used_survey_blocklist#17]
It is blocking images on this site: https://ideas.ccleaner.com/32
Further information on Cloudinary: https://better.fyi/trackers/dwgyu36up6iuz.cloudfront.net/

**Comment by Kees1958** [comment]
changed to  ||cloudinary.com$cookie,third-party 

@vtvksmy thanks for opening issue, could you check whether blocking cookie (AdGuard syntax) only solves this problem?

AdBlockers incapable of blocking cookies will probrably ignore this line, so I hope it does not provide problems

**Comment by vtvksmy** [comment]
I'm using the Edge Blocklist method, so I can't check but I believe it should solve the problem for users of adblockers.
