### ISSUE TITLE
Consider adding domains from "better.fyi" project

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#18]
Thanks to @vtvksmy we should compare our own with this list:
https://better.fyi/trackers/

**Comment by Kees1958** [comment]
Yes, they state what they are blocking, that is why I started to use $cookie rule from AdGusrd. Feel free to add missing trackers when they appear more than 10 times in the list they use (user suggested and trackers in alexa top 500)

**Comment by Kees1958** [comment]
I have removed the domains in your BeerIsGoodList which are already present in Edge default lists (Advertising, Analyrics, Cryptomining and Fingerprinting). This is the reason that the domain count is lowered. 

I also thought it is  a good idea to standardize the file naming. Added a warning in the old file to use the file with the correct naming convention.

**Comment by Kees1958** [comment]
I took 25 samples from better.fyi all except 2 were already included in our list. The 2 not included had a very low prevalence, so it is probably a lot of work for little added value to manually go through their list. Also because their product is paid, they may not agree in using their data. So I am not putting any effort in it.

**Comment by Kees1958** [comment]
@beerisgood Yesterday evening I took first 100 of FYI list from blocklist.com and all 100 were already in our list.

Based on these two experiments (25 random and first 100) I would say we are well covered, no need to put effort in it and possibly infringe on IP issues with this paid MAC extension

**Comment by beerisgood** [comment]
Awesome!
