### ISSUE TITLE
Chat breakage on https://support.nordvpn.com/FAQ/Setup-tutorials/

### ISSUE THREAD

**Issue by crssi** [Kees1958/W3C_annual_most_used_survey_blocklist#19]
We have a chat breakage on site `https://support.nordvpn.com/FAQ/Setup-tutorials/` due to rule `||pusher.com$3p`.
Using more specific rule `||pusher.com$3p,~xhr` wold do. Or neutering with `@@|pusher.com$3p`.

STR:
1. open `https://support.nordvpn.com/FAQ/Setup-tutorials/`
2. click on question mark icon on the bottom-left corner

Cheers

**Comment by Kees1958** [comment]
I had a look at pusher.com, it is user collaboration and activity management software to engage with users. Although it can be used for location and user tracking, it is not an advertising or tracking network. As far as I can determine the user should be known in the first place to be able to track them. Although user activity and geo tracking are one of the use cases, it is not tracking users like facebook that does. I guess the XMLHTTPrequest probably sends the data, allowing xhr would make it useless to include pusher.com. Therefor I suggest to remove it from the EU_US_most common lists.

**Comment by Kees1958** [comment]
removed

**Comment by crssi** [comment]
Thank you for your swift action.

Wish you best
