### ISSUE TITLE
commen or common?

### ISSUE THREAD

**Issue by crssi** [Kees1958/W3C_annual_most_used_survey_blocklist#20]
I guess you have a typo all over the place and you should use word `common` instead of `commen`. 😉 

Cheers

**Comment by Kees1958** [comment]
thx

**Comment by Kees1958** [comment]
It is in the file name, so it I keep it as it is. BeerIsGood is from Germany, I am from Holland, so I hope our users will forgive us (same thing happened with referer, which should be referrer)

**Comment by crssi** [comment]
No problem.
Its was not meant as a request for change, more for info. 😉 
Cheers ❤️

**Comment by Kees1958** [comment]
@crssi new files with new names created

TOP_EU_US_Ads_Trackers_ABP
TOP_EU_US_Ads_Trackers_EDGE
TOP_EU_US_Ads_Trackers_HOST
