### ISSUE TITLE
When to delete old files?

### ISSUE THREAD

**Issue by Kees1958** [Kees1958/W3C_annual_most_used_survey_blocklist#21]
@beerisgood 

I removed the TOP500 (as I had warned in the header). When do you suggest we should remove the old duplicates"

BeerIsGood_Edge_blocklist >> use EU US most commen ads & trackers in HOST format

EU_US_most_common_trackers >> use EU US most commen ads & trackers in ABP format

**Comment by beerisgood** [comment]
I would use the same warning time you use for Top500 list 👍

**Comment by Kees1958** [comment]
per 1 january 2021
