### ISSUE TITLE
Changing file names for easier handling

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#22]
We can avoid problems like https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/20 and also decrease readability problems like:
![image](https://user-images.githubusercontent.com/9625159/101026214-e9cef680-3576-11eb-9538-e793970cb2b5.png)

The URL is also strange too for e.g.:
`https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU%20US%20most%20commen%20ads%20%26%20trackers%20HOST%20format`

My suggestions are the following file names:
- W3C_EU-US_ABP-format
- W3C_EU-US_EDGE-format ("Edge" written in capital letters to be the same as other file names)
- W3C_EU-US_HOST-format

or easier:
- W3C_EU-US_ABP
- W3C_EU-US_EDGE
- W3C_EU-US_HOST

This also can be done before https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/21 is solved

**Comment by Kees1958** [comment]
Yep, go ahead, change them (and change commen to common :-)

**Comment by beerisgood** [comment]
It's your baby :)

Did you really want adding number? Numbers can change so i personally wouldn't add one in the file name.
Is that okay?

**Comment by Kees1958** [comment]
TOP_EU_US_Ads_Trackers_ABP /EDGE / HOST
