### ISSUE TITLE
Edge blocklist

### ISSUE THREAD

**Issue by Kees1958** [Kees1958/W3C_annual_most_used_survey_blocklist#25]
Since Microsoft was so kind to move the Other file, what is your take @beerisgood on the use of this list? My experience with Microsoft is that they occasionally implement other use cases by first restricting/disabling something and when they have incorporated a feature into regular use, allow it again.  So while it is made clumsy/near impossible to use now, shall we keep maintaining the Edge list until the start of Q3 of 2021?

**Comment by beerisgood** [comment]
From [Microsoft](https://www.reddit.com/r/MicrosoftEdge/comments/kfikaj/trust_protection_lists_folder_is_empty_with/ggagi05/):

> We’re in the process of updating the TPL component to improve the amount of protection provided. What you’re seeing is the first step of that. We always push out a version of the TPL component with the installer for Edge, so you are protected regardless of the update status on edge://components. You should see an updated list in the application directory (for example: C:\Program Files (x86)\Microsoft\Edge\Application\87.0.664.66\Trust Protection Lists), and it will only show up in your local app data path when it’s updated via the component updater. Since that’s currently not happening, you will not see it in the local app data path.

The same file(s) also exists at:
`C:\Program Files (x86)\Microsoft\Edge\Application\87.0.664.66\Trust Protection Lists\Mu`

Tracking Prevention still works and editing the Other file from that folder (need admin rights) still works but it's inefficient as the path change with every browser update. 
So they doesn't move the file actually but rebuilding the whole system. Let's wait until they finish.

**Comment by Kees1958** [comment]
Agree
