### ISSUE TITLE
Remove ampproject.org from Edge list

### ISSUE THREAD

**Issue by vtvksmy** [Kees1958/W3C_annual_most_used_survey_blocklist#26]
"Blocking all content may break sites when they rely on AMP for functionality, so we only block cookies for now."

Source: https://better.fyi/trackers/ampproject.org/

**Comment by Kees1958** [comment]
Done, thanks for your valuable input. In the ABP list I have $cookie (only works with AdGuard)

**Comment by beerisgood** [comment]
Remember AMP is from Google so you may share your data with them on such sites.

@vtvksmy
