### ISSUE TITLE
Loading in Pi-Hole

### ISSUE THREAD

**Issue by stevefxp1** [Kees1958/W3C_annual_most_used_survey_blocklist#27]
When I am updating Pi-Hole by pulling https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_HOST, I am getting the following errors: 
[i] Target: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_HOST
  [✓] Status: Retrieval successful
  [i] Received 2 domains, 2 domains invalid!
      Sample of invalid domains:
      - content="github.com">
      - content="github.com">

If you need anything additional please let me know.

Thanks,
Steve

**Comment by beerisgood** [comment]
The file doesn't include "content="github.com" lines.
PiHole parsing is corrupt.

You should also use the raw file: https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_HOST

**Comment by beerisgood** [comment]
@stevefxp1 PiHole mistakenly parses the [comment line](https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_HOST#L7) which ends up blocking Github.
But that's their fault, not ours.
