### ISSUE TITLE
Won’t load Twitter images

### ISSUE THREAD

**Issue by Greigh** [Kees1958/W3C_annual_most_used_survey_blocklist#28]
At least on iOS mobile filtering through with DNS, Twitter images are not appearing. 

I believe it is this one but I could be wrong: syndication.twitter.com. 

Also you should add ads.Twitter.com as it's a tracker that is getting through.

Thanks for your hard work.

**Comment by Kees1958** [comment]
added ads.twitter.com and removed syndication.twitter.com please check whether problem is solved

**Comment by Greigh** [comment]
Oops. You can re-add syndication. I found the actual issue: twimg.com.

**Comment by beerisgood** [comment]
I re-add `syndication.twitter.com` and replace `||twimg.com$cookie,$cookie,third-party` with `||twimg.com$cookie`
@Kees1958 the line was incorrect. See "$cookie" twice

Please test if this solve your problem.

**Comment by Greigh** [comment]
All fixed :)

**Comment by beerisgood** [comment]
Thanks for feedback!
