### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kees1958** [Kees1958/W3C_annual_most_used_survey_blocklist#31]
@beerisgood 

I would like to remove all google and social media related bocks and put them in a separate list (only ABP) format.

What are you thoughts about that?

**Comment by beerisgood** [comment]
Are you sure? Google is one of most tracking company.

Also more lists mean more maintenance

**Comment by Kees1958** [comment]
OKay,

I will drop this idea. Could you resend the chat request. When I clicked on it, it did not work so I thought you had revoked it. Now I realize that AdGuard stealth mode probably stripped the URL parameters which caused the 404 not found result.

**Comment by beerisgood** [comment]
@Kees1958 i don't revoke it but remove and re-add you.

**Comment by Kees1958** [comment]
??? something is not working ???
![image](https://user-images.githubusercontent.com/30925856/104501770-73df9580-55e0-11eb-9764-0615c39e2c2f.png)

**Comment by beerisgood** [comment]
Sounds like you block something on your end.
I never got any problems with invitations.

But glad you solved it :)

as soon as you have read this message, you can remove the posts about it here, as they do not belong to the project.
