### ISSUE TITLE
Consider removing linkedin.com

### ISSUE THREAD

**Issue by madlymad** [Kees1958/W3C_annual_most_used_survey_blocklist#34]
I've tried to access https://linkedin.com/ which after DNS resolution automatically redirects to https://www.linkedin.com/

I've whitelisted it in my end but it seems to me that it should not be part of the list!

**Comment by beerisgood** [comment]
Fixed!

@Kees1958 i guess we should remove this in ABP list too?

**Comment by Kees1958** [comment]
Thx yes, done that
