### ISSUE TITLE
Difference between lists?

### ISSUE THREAD

**Issue by holow29** [Kees1958/W3C_annual_most_used_survey_blocklist#35]
Is there a difference between the three lists other than format? I do see some domains (for example forbes.com) are blocked on ABP and hosts but not Edge.

**Comment by Kees1958** [comment]
Yes besides format the ABP list only blocks third-party, while host blocks all (first-party and third-party requests). When you would hoave visiyed Forbes with ABP list it probably woud not break, while using the HOST list the webisitw would be blocked or be corrupted (e.g. no stylesheet, pictures missing etc).
