### ISSUE TITLE
Possible domains to remove

### ISSUE THREAD

**Issue by holow29** [Kees1958/W3C_annual_most_used_survey_blocklist#36]
There seem to be quite a lot of domains on here that break websites. Here is a list of some of them:

This is based on the Hosts list, so I am not sure how applicable it is to the others.

**Used in multiple websites/services:**
ampproject.org
adobedtm.com
akamai.com
bazaarvoice.com
firebase.google.com
sabre.com
scene7.com

**Websites themselves:**
adobe.com
att.com
booking.com
carrefour.es
collegehumor.com
complex.com
corporate.trovit.com
corporate.walmart.com
createjs.com
crutchfield.com
dailymotion.com
delta.com
expedia.co.uk
experian.com
flixbus.com
forbes.com
foursquare.com
glassdoor.com
help.overstock.com
help.snitcher.com
heraldweekly.com
housing.com
justwatch.com
kayak.com
landsend.com
mailchimp.com
philips.com
phonearena.com
qantas.com
qualtrics.com
rackspace.com
shutterstock.com
stackpath.com
subscribe.hearstmags.com
target.com
touchcommerce.com
uk.hotels.com
wayfair.com
wish.com

**Comment by Kees1958** [comment]
Thanks we should remove them all

**Comment by beerisgood** [comment]
AMP Sites like ampproject.org use Google backend so they can easier track.

**Comment by holow29** [comment]
Yes, the ones that I separated into the top category are all more likely to track, with the exception of sabre.com (an airfare booking system used by airlines):

- adobedtm is Adobe's Dynamic Tag Management service that some websites use - to be honest, I think I've only encountered 1 site that breaks using it, so I view that one as less important.
- Akamai is a CDN
- Bazaarvoice is a service used on many shopping sites
- firebase is also a Google platform some sites use
- scene7 is an Adobe service that publishing sites use

**Comment by Kees1958** [comment]
All removed except:
assets.adobe - tag management
touchcommerce.com- customer engagement 

@holow29 thanks for the feedback. I have accidentally used a source which I initially rejected (with last years major update), 
I remember finding carrefour.es (not france), quantas, booking, kayak and forbes (Forbes triggered me), thanks for your hard work. Really appreciate your feedback.

@beerisgood I have updated ABP and HOST. It is up to you to keep EDGE list (and maintain it) or remove it

**Comment by beerisgood** [comment]
@holow29 thanks for feedback

**Comment by beerisgood** [comment]
@Kees1958 i wait until Edge 88 (release should coming next days) and if the problem isn't fixed, i will delete Edge list.
A up2date backup is in my fork.

**Comment by beerisgood** [comment]
Edge 88 stable is out, without a fix.
So, i remove my Edge list for now.

**Comment by holow29** [comment]
glassdoor.com
expedia.co.uk

These two domains seem to still be present; I am not sure if you meant to remove them or not.

**Comment by Kees1958** [comment]
Removed thanks
