### ISSUE TITLE
Some issues to discuses

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#39]
like my latest two commits https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/b1c99475316f30c26297bed3c481a19df6e2aa17 & https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/1fb4680efb554e8e4cca61cde44e85629839b813 i would like to discuss this post from https://oisd.nl/ maintainer after i ask adding our list:

> The list was added, removed, added, removed.
I keep finding things in there that make that list more problematic than usefull.
Latest false positive I found in there; thomann.de, Europe's largest store for musical instruments and studio, lighting and sound technology.

so, i fix this but he told me other issues:

> 9c9media.ca # Crave.ca video streaming platform, app and website streaming.
> analytics.twitter.com # Following links in tweets stops working as it redirects through this domain
> aweber.com # newsletter
> combell.com # belgian hosting company
> gleam.io # mostly for giveaways
> godaddy.com # Domain Names, Websites, Hosting ...
> googleadservices.com # google shopping links
> googletagmanager.com # FreshChat on DesignBold
> googletagservices.com # nfl.com videos; http://www.nfl.com/videos/up-to-the-minute/ clicking videos below will not work otherwise
> infonline.de # a Fedora repository
> klaviyo.com # needed for https://kith.com/pages/apparel-sizing
> nielsen.com # Nielsen Holdings PLC is an American information, data and measurement firm. Nielsen operates in over 100 countries and employs approximately 44,000 people worldwide. The company is listed on the New York Stock Exchange and is currently a component of the S&P 500
> sc-static.net # user report needed for something in snapchat app
> segment.io # Cruchyroll Subtitles
> sfr.fr # french mobile ISP
> simply.com # "We are working a project on this domain, that does not have anything to do with advertising or tracking"
> snap.com # Snapchat's corporate site.
> tags.tiqcdn.com # Channel list on T-Mobile's TVision website won't load otherwise (after inputting ZIP code... you can do 90001)
> tchibo.de # Tchibo App
> thecounter.com # burger joint
> thomann.de # Largest european music equipment retailer
> tinypass.com # logging into several publishers sites (with paid subscription).
> trackcmp.net # unsubscribe from a legitimate bulk mail
> vendorlist.consensu.org # vi.nl cookie warning
> zaful.com # clothing store

What are your opinons about?

**Comment by Macqael** [comment]
Actually i see the very same problem in W3C list than in the duckduckgo tracker privacy.
Too many false positive who totally break the navigation so in some case i can understand they have removed it.

**Comment by Kees1958** [comment]
From the list provided only twitter, google and segment.io are used in analytics, tagging and tracing. As posted last year I made a mistake using a source which I intended not to use. I browsed through the list and removed the ones which I recognized as 'over ambitious' blocking. Nielsen for instance also provides postcode based marketing info, so making it appear on the tracking list did not trigger an alarm for me. 

We already made the principal decision to always remove false positives. So I am inclined (when you agree) to also apply this guideline  for analytics, tagging, segmenting, usability, A-B testing and tracking services which cause problems. In short when something causes problems, lets remove it from the list. What is your take on this?

**Comment by beerisgood** [comment]
The problem is that only few people use this list/ know it.
That's why I try adding it to other projects like OISD.

After the bad source, did you remove everything from it? I mean is the current state only based on W3C?

Sure we should solve false positives but also keep breakage as less as possible. What's what OISD maintainer also do

**Comment by Kees1958** [comment]
Yeah I really appreciate getting more feedback. Would you remove the domains you posted?


Let’s remove all domains causing troubles.  I thought I had removed most bad websites. Manually checking now with 500 domains at a time. That is why you see the number of domains decreasing.

I don’t wat to import raw sources again since we have curated them. 

Verzonden vanuit Mail voor Windows 10

Van: beerisgood
Verzonden: zondag 14 februari 2021 10:06
Aan: Kees1958/W3C_annual_most_used_survey_blocklist
CC: Kees1958; Comment
Onderwerp: Re: [Kees1958/W3C_annual_most_used_survey_blocklist] Some issues todiscuses (#39)

The problem is that only few people use this list/ know it.
That's why I try adding it to other projects like OISD.
After the bad source, did you remove everything from it? I mean is the current state only based on W3C?
Sure we should solve false positives but also keep breakage as less as possible. What's what OISD maintainer also do

**Comment by beerisgood** [comment]
Yes, i would like to remove all these domains so we got a less false positives and breakage for now and in future.
Anyway it's your baby so i want you're okay for that big move.

**Comment by Kees1958** [comment]
Well, you have author rights, so feel free to add and delete domains. I am cleaning it up slowly (500 at a time), so when you see false positives delete them or want to add domains just do it and inform me afterwards in this issue . I can see what domains are added/deleted in the history, so just mention reason why in this issue

**Comment by beerisgood** [comment]
Done. I also add all removed domains to https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/RemovedDomains and sort all domains (in both files) alphabetically.

Now i will start sane cleaning on ABP list.

**Comment by Macqael** [comment]
@Kees1958 i think you can do 3 version of the list, first light (who remove all potential problem), one normal (who contain analitics), and the big one full, who have even the false positive.
Like that the user can choose the version he want.

**Comment by Kees1958** [comment]
@Macqael 

Well, I am afraid that would triple the maintenance effort also, so although a tempting idea, it does not seem feasible in terms of time. Thanks for the suggestion.

**Comment by Kees1958** [comment]
@beerisgood 

Found this ranking of advertisement exchange platforms. My experience is that a marketshare lower than 0.25 or so is sufficient everything with a lower market presence can be omitted. https://www.adstxt.com/exchanges

When you want and got the time, you could check whether we miss one.

Thanks 

Kees

**Comment by Kees1958** [comment]
@Yuki2718

Is there a way to see which domain is rejected bu uBlockOrigin. uBO reports 3805 used out of 3806 The one rejected is probably a typo or duplicate (sinds I started to use .*) 

Regards Kees

**Comment by Yuki2718** [comment]
@Kees1958 Hi, the easiest way is that first open the logger, choose "All", and add/update the filter list in question:

<details>
<summary>Screenshot</summary>

![logger](https://user-images.githubusercontent.com/58900598/108621966-4c9aa480-7479-11eb-9062-d93d5617db43.png)

</details>

So `||ytimg.com$cookie,third-party` is rejected as uBO doesn't support `$cookie` and `||hitx.com$third-part` is obvious typo.

**Comment by Kees1958** [comment]
@Yuki2718 a left over of the AdGuard $cookie and a type, thanks for the help

**Comment by beerisgood** [comment]
I close the discussion for now as original topic is solved.
Let's keep the list always clean 👍
