### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Haarolean** [Kees1958/W3C_annual_most_used_survey_blocklist#41]
Hi, I'm using your adlist as a part of firebog.net 'safe' ticked list.
I've encountered some false positives, or, possibly, too restrictive behaviour.
For example, there's russian 'google' called yandex with its own [maps](https://yandex.ru/maps/) which doesn't work at all with this adlist since all the js from yastatic.net is being blocked.
Examples:
https://yastatic.net/react/16.8.4/react-with-dom.min.js
https://yastatic.net/s3/front-maps-static/maps-front-maps/build/client/desktop/chunks/base/5de0907fcd45e1f3295f.ru.js
https://yastatic.net/weather/i/icons/funky/dark/bkn_d.svg
Could you please edit the list to avoid these things? Thank you.

**Comment by beerisgood** [comment]
Thanks for reporting.
Fixed!

**Comment by Haarolean** [comment]
@beerisgood thank you very much! It might host some ads there as well, but I don't know exact regex matches and probably it could be mixed altogether.

**Comment by beerisgood** [comment]
This is first party problem like it exist with YouTube.

Easiest way to circumstances such problems is supporting the site with some kind of ads-free account.
