### ISSUE TITLE
This list blocks hp.com

### ISSUE THREAD

**Issue by louisgtwo** [Kees1958/W3C_annual_most_used_survey_blocklist#46]
TOP_EU_US_Ads_Trackers_HOST

This blocklist has hp.com. Does the whole domain need to be blocked?

**Comment by beerisgood** [comment]
@Kees1958 is that from removed bad source?

**Comment by Kees1958** [comment]
Yes, ☹ 

Verzonden vanuit Mail voor Windows 10

Van: louisgtwo
Verzonden: dinsdag 30 maart 2021 06:34
Aan: Kees1958/W3C_annual_most_used_survey_blocklist
CC: Subscribed
Onderwerp: [Kees1958/W3C_annual_most_used_survey_blocklist] This list blockshp.com (#46)

This blocklist has hp.com. Does the whole domain need to be blocked?

**Comment by beerisgood** [comment]
@louisgtwo its fixed: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/fc4dc398804b82230ff71764219d9375823274ad

Thx for feedback
