### ISSUE TITLE
i am off

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#50]
I have tried persistently and often to have this list integrated into others such as OISD. (among other things, this is where the big clean-up came from https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/aa45cf33a08c31d52bf8bcfd8c03ef38502f74ac)

Unfortunately, the (now removed) erroneous source left even more false positives and although this list was (again) added to OISD, it has now been removed again and it seems there won't be another time.

Since other list maintainers are too ignorant or don't even reply, i don't see any way to integrate this list into larger ones at the moment.

In my opinion, going back to the status quo before the faulty source is best start, but even this will not allow integration into known lists without starting as a completely new project.

Long story, short: i am currently no longer interested in the project, as my primary focus is on DNS blocking anyway.
To be fair, i did not want to leave these points unmentioned. In this sense bye 🍺 and good luck 🍻

**Comment by Kees1958** [comment]
OK, noted thanks

**Comment by spirillen** [comment]
I get your point @beerisgood :smile: 

https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/260ad525dbdf279f95c9c78d824b033a6883f0e0/RemovedDomains#L14-L16

These are for sure to be in ALL BlackLists.

**Comment by beerisgood** [comment]
> I get your point @beerisgood 😄
> 
> https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/260ad525dbdf279f95c9c78d824b033a6883f0e0/RemovedDomains#L14-L16
> 
> These are for sure to be in ALL BlackLists.

Obviously you don't know what you're talking about.
See e.g. https://oisd.nl/excludes.php

Anyway that isn't the topic here.
@Kees1958 please close comments here.
