### ISSUE TITLE
False positive: newrelic.com

### ISSUE THREAD

**Issue by yiyang-dev** [Kees1958/W3C_annual_most_used_survey_blocklist#51]
newrelic.com is far too broad; this is a legitimate monitoring/metrics that isn't just used to serve ads. The control panel for signed up services is covered under this domain

**Comment by Kees1958** [comment]
I am dropping support of the HOST file version. It was used by BeerIs Good to plug this list at other github repositories. I am using the ABP version. I will continue to update that version.

**Comment by Kees1958** [comment]
Removed from HOST
