### ISSUE TITLE
This list breaks instagram.com

### ISSUE THREAD

**Issue by d4k0** [Kees1958/W3C_annual_most_used_survey_blocklist#56]
Hi,

according to uBlock Origin this list breaks/blocks instagram.com and prevents it from loading properly.

This seems to be the filter that is causing it:

||facebook.$3p,domain=~facebook.com|~messenger.com

There are probably more filters that are involved in this as I had no luck making the site work again.

**Comment by Kees1958** [comment]
@dk40, thanks I changed the rule to

||facebook.*,domain=~facebook.com|C~messenger.com|instagram.com$third-party

could you check whether the problem still occurs?

**Comment by d4k0** [comment]
Thanks, it's working now!
