### ISSUE TITLE
Regular HOST not available anymore

### ISSUE THREAD

**Issue by PieterWaegeman** [Kees1958/W3C_annual_most_used_survey_blocklist#59]
I use the file TOP_EU_US_Ads_Trackers_HOST for my PiHole installation. Since a couple of hours, this is not available anymore.
Will the current ABP-file be converted to a HOST-file and used next to each other?

**Comment by Kees1958** [comment]
Pieter,

I am sorry, but the host file was maintained by BeerIsGood. He left the project. It was a bit to much for me to maintain two versions. 

So as long as I am the only maintainer, I won't be supporting a host file format. When other people want to help by becoming a maintainer, feel free to send me a message.

Regards

Kees

**Comment by Crypto-Spartan** [comment]
@Kees1958 What is different between the ABP list and the Hosts list? Just the format, or the domains themselves?

I also used this for pi-hole and am unable to use it now.

**Comment by Kees1958** [comment]
It was just the format, but since Adguard and uBlockOrigin support wildcards e.g google.* for all google domains, it can't be converted anymore

**Comment by Crypto-Spartan** [comment]
i feel like it would be easy to write a script/program that converted the format super easily, im really surprised this wasn't done before. one of the things the script could look at is whether or not there is a `*` in the domain, and skip that domain if it's there.

**Comment by Crypto-Spartan** [comment]
@Kees1958 I wrote this in rust, let me know if you'd like to incorporate it

https://gist.github.com/Crypto-Spartan/8db843c3e9d16dd28a12d4bb5d39d5bd

**Comment by Crypto-Spartan** [comment]
@Kees1958 I wrote this in rust, very basic command line tool that will convert the list from ABP format to HOST format

https://gist.github.com/Crypto-Spartan/8db843c3e9d16dd28a12d4bb5d39d5bd

**Comment by Kees1958** [comment]
@Crypto-Spartan 

Thanks, but why don't you fork this list and create the host file format yourself?

Regards Kees

**Comment by Zelo72** [comment]
I use Kees lists in my generated blocklists and convert them for the lists in domain and host format.

Current doamins only versions can be found at:

https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/sources/kees1958_w3c_annual_most_used_survey_blocklist_eu_usmost_used_ad_and_tracking_networks.txt

https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/sources/kees1958_w3c_annual_most_used_survey_blocklist_top_eu_us_ads_trackers_abp.txt

**Comment by Crypto-Spartan** [comment]
@Kees1958 The main reason I offered to add it here was because I knew other people used this list for pihole and I wanted to be able to help them out. Also, I don't know of a simple way to automate the update process for the blocklist in a forked repo.

@Zelo72 Are you automating the updates to the blocklist from this repo or do you have to perform them manually?

**Comment by Zelo72** [comment]
@Crypto-Spartan Hi, the sources are automatically updated twice a day with my blocklists.

**Comment by Kees1958** [comment]
I leave this issue open, so people can use Gerd's (Zelo72) version. allright with @Crypto-Spartan and @Zelo72

**Comment by Zelo72** [comment]
@Crypto-Spartan @PieterWaegeman @Kees1958 

I have provided a more official version of Keess lists in domain and host format. These are updated daily and include the following sources:

```
1. adblock - https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US%2Bmost_used_ad_and_tracking_networks
2. adblock - https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_ABP
```

The following whitelist is taken into account when creating:

`https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/RemovedDomains`

Links to the blocklists:

Hosts: https://raw.githubusercontent.com/Zelo72/hosts/main/kees1958.txt
Domains: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/kees1958.txt

Greetings,
Gerd - https://github.com/Zelo72

**Comment by Kees1958** [comment]
Thanks Gerd, well done

**Comment by Kees1958** [comment]
@Zelo72 

Gerd thanks for the mail removed ||cedexis.com$third-party ||cedexis.net$third-party

**Comment by DEberhardt** [comment]
Zelo72 has left the building?

Found a replacement list here:
https://github.com/dead-hosts/Zelo72s_rpi.pihole.blocklists.multi
and
https://github.com/dead-hosts/Zelo72s_rpi.pihole.blocklists.fake

Don't know how to use them yet...

**Comment by DEberhardt** [comment]
As I am not using PiHole yet (wanted to look into it since forever), I have created myself a little script to convert the list above into a Host list to import into my HOSTS file manually. Hope you can use it.
https://github.com/DEberhardt/PsScriptSnip/blob/main/Scripts/misc/Update-KeesHostsList.ps1

**Comment by Kees1958** [comment]
@DEberhardt @Crypto-Spartan 

Why don't you join forces and create a fork. The update frequency is low and with Github actions it seems to be possible to run a scheduled task which takes care of the syncing

![image](https://user-images.githubusercontent.com/30925856/152676562-2e3cbd85-06c2-43ef-a6b0-fa1583d5a20f.png)

**Comment by DEberhardt** [comment]
What a splendid idea :) - I am dipping my toes into Github actions right now, good thing to learn it properly :)
