### ISSUE TITLE
Reporting potential false-positive.

### ISSUE THREAD

**Issue by Wicloz** [Kees1958/W3C_annual_most_used_survey_blocklist#62]
I'm talking about your blocklist at https://github.com/Zelo72/rpi/blob/master/pihole/blocklists/kees1958.txt
This has [ipify.org](https://www.ipify.org/) on it, one of many websites which will give you your IP address.

Are you sure it should be on that blocklist? If so that's fine.

In my case, since I block subdomains for any blocked domains too, the API endpoints became inaccessible and several of my scripts that get the IP address through that site broke ...

**Comment by Kees1958** [comment]
@Wicloz 

Removed it with some other IP information websites. Because they are used a lot they must have been sneaked in. 

Thanks for reporting

**Comment by Wicloz** [comment]
Can confirm this solves the issue, thanks for the quick fix, although I only noticed it now.
