### ISSUE TITLE
trafficjunky

### ISSUE THREAD

**Issue by loupsoliste** [Kees1958/W3C_annual_most_used_survey_blocklist#69]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/9e39b19f66c20a62a0aadb3cedc8ee361597b915/EU_US%2Bmost_used_ad_and_tracking_networks#L4948

hi,
you have 3 entries for this domain ,
maybe a typo

thanks

**Comment by Kees1958** [comment]
@loupsoliste 

The trafficjunky.* should replace trafficjunky.com and .net. I added the wildcard * but forgot to remove .com and .net entries

Thanks
