### ISSUE TITLE
chtbl.com possible typo

### ISSUE THREAD

**Issue by loupsoliste** [Kees1958/W3C_annual_most_used_survey_blocklist#70]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/1ebab7ba7784108869253d43725b3d6d829c59f7/EU_US%2Bmost_used_ad_and_tracking_networks#L1052

salut,
script for scfipt ?

good day

**Comment by Kees1958** [comment]
Thanks for posting the issue, solved
