### ISSUE TITLE
Breaks on Pi-Hole Import

### ISSUE THREAD

**Issue by mikep11** [Kees1958/W3C_annual_most_used_survey_blocklist#73]
When updating adlist on Pi-Hole, received the following:

>   [i] Target: https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US+most_used_ad_and_tracking_networks.txt
  [✓] Status: Retrieval successful
  [i] Imported 1 domains, ignoring 6858 non-domain entries
      Sample of non-domain entries:
        - !
        - 1.1]
        - at
        - only)
        - ||0emm.com$third-party

**Comment by hagezi** [comment]
@mikep11 This is a list in AdBlock format. This format is not supported by Pi-hole. You can only use lists in domain or hosts format.
