### ISSUE TITLE
"Addendum_to_Edge_Firefox_build_in.txt" receives fewer updates than the other 2 lists

### ISSUE THREAD

**Issue by SampeiNihira** [Kees1958/W3C_annual_most_used_survey_blocklist#74]
Hi Kees1958,
does this happen because this list in Edge or Firefox can be replaced with the other 2 lists?
Or is there another reason?
TH.

**Comment by Kees1958** [comment]
I am sorry @SampeiNihira this is why.

Edge has two policies, I noticed that some changes were included in Edge standard mode (default blocks cookies mostly). Therefor I added them to both big list and the MV3 Top1000, so you might need to add the MV3 on top of the addendum.

**Comment by SampeiNihira** [comment]
Hi,
I use **strict** mode.
Do you recommend only the MV3 list?

**Comment by sillyjaybird** [comment]
@Kees1958 So your advise is to use both MV3 and Addendum?

**Comment by Kees1958** [comment]
Major update, expect some false positives, apologize in advance
