### ISSUE TITLE
A error a 1 rule in the list EU US most used advertising supplement for Edge and Firefox build-in

### ISSUE THREAD

**Issue by Mercyletter** [Kees1958/W3C_annual_most_used_survey_blocklist#77]
Hi, when viewing the list in the ublock panel, I get this line as an error. I attach a screenshot. I am using on Windows 11. Best regards and thank you very much.

![Captura de pantalla 2023-06-09 141555](https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/assets/32906745/7ad7091e-f9b7-472d-ba98-800fdd78d656)
||cdn.segment.*/analytics.js/$^third-party

**Comment by Kees1958** [comment]
Yes, I copied the wrong source, It should be OK now, can you confim please ?

**Comment by Mercyletter** [comment]
Thank you very much, solved. All the best.
