### ISSUE TITLE
typos in your 3 lists

### ISSUE THREAD

**Issue by loupsoliste** [Kees1958/W3C_annual_most_used_survey_blocklist#79]
Hello,

I have checked your 3 lists and i found some typos

||adtelli.comt  in lists mv2 and addendum
||atlassolutions.com    $third-party is missing in list addendum
||commissionfactory.com   $third-party is missing  in list addendum
||freewheel*$third-party  a dot is missing in list addendum
||ggpht.com^$third-party  you have removed it from list mv2 but it still is in list mv3
||gstatic.com,  in lists mv2 and addendum
||jwpltx.com^$third-party$third-party in list mv3
||metakeyproducer.com^^$third-party in list mv2  and in list addendum  $third-party is missing
||newtention*$third-party   a dot is missing in list addendum
||oneaudience.^$third-party  isn't missing a tld in lists mv2 and addendum
||onetrust.com,ping^$third-party  isn't the correct line ||onetrust.com$third-party,ping in list mv2
||pdst.fm$script,third-party^$third-party  isn't the correct line ||pdst.fm^$script,third-party in list mv2
||sift*third-party  a dot is missing in list addendum
A line is missing between ||tnctrx.com^$third-party and ||tns-cs.net^$third-party in list mv2
||wc4.net$image,third-party^$third-party  isn't the correct line ||wc4.net^$image,third-party in list mv2

and ||tf1.fr^$third-party break tf1info.fr,thr player is missing  with this line ||tf1.fr^$third-party,domain=~tf1info.fr it works

Thanks in advance, and sorry for not replying  the last time, "stuff happened" and i forgot

**Comment by Kees1958** [comment]
Thanks a lot for informing me, that is much appreciated. 

Delay in correction due to holiday

Thanks for your hard work

**Comment by loupsoliste** [comment]
Hi,
no problem, 
its for that i have a account
thanks to you
