### ISSUE TITLE
delivr.com 

### ISSUE THREAD

**Issue by p1r473** [Kees1958/W3C_annual_most_used_survey_blocklist#82]
QR code URL shortener service
False positive

Darn I just realized host file version has been discontinued. I dont use abp, I use pihole...
Request to bring back domain version

**Comment by spirillen** [comment]
`delivr.com` is all tracking, and when it comes to security... just never use any such thing as you never know what will happen, where are you routed to, what executable or macro is lunched, it is a trojan, worm, virus or cryptoware?? just blacklist these things faster than they appears.

**Comment by Kees1958** [comment]
@spirillen 

So what is the verdict? Keep it blocked?

**Comment by Kees1958** [comment]
> QR code URL shortener service False positive
> 
> Darn I just realized host file version has been discontinued. I dont use abp, I use pihole... Request to bring back domain version

Sorry that is to much work.

**Comment by yokoffing** [comment]
https://delivr.com/page/707/data-policy

Seems fairly sensible to me. I think it's a bit extreme to block this; it should be optional.

**Comment by Kees1958** [comment]
removed
