### ISSUE TITLE
Yandex completly blocked

### ISSUE THREAD

**Issue by hagezi** [Kees1958/W3C_annual_most_used_survey_blocklist#86]
See:

https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/5a9f9fef25f6cfa38dedb3a0f456870fc17a4f1e/addendum_to_Edge_Firefox_build_in.txt#L5174

https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/5a9f9fef25f6cfa38dedb3a0f456870fc17a4f1e/EU_US_MV3_most_common_ad%2Btracking_networks.txt#L2571

**Comment by Kees1958** [comment]
Yep, don't use it (for EU and US purpose). But I will remove that line and make a small personal tracking list

**Comment by Kees1958** [comment]
@hagezi

Gerd I have a few questions: 

Are you using those filters and if so in which? 

Have you ever considered publishing a highly condensed anti-trackers list (which also blocks adss a side effect by blocking the networks which deliver the ads as explained in Peter's Low and my Read me).

If so this list should consist of 
1. Peter Low's list
2. AdGuard's (https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt)
3. My Mv3 most used
4. My Addendum to Edge and Firefox

**Comment by hagezi** [comment]
Hi @Kees1958,

I started analysing the lists and noticed the ‘false positives’. My lists are DNS lists based on native plain domains, which means that if I use an adblock list as a source, I have to ‘convert’ all rules that contain an asterisk into plain domains. To do this, I use merged Top 1/10 million lists (Umbrella, Tranco, Chrome, Cloudflare, DomCop, ...) from the last 12 months. 
After further processing, the other list formats are generated from the overall domain list.
The AdBlock DNS lists are compressed and may only contain ‘native’ rules (`||domain.tld^`) so that they are compatible with all possible DNS blockers. Rules with an asterisk are not supported by all Adblockers.

My lists are not 1:1 copies of sources, see here: https://github.com/hagezi/dns-blocklists/wiki/FAQ#sources

As my DNS lists mainly contain only popular domains, i.e. those that are actually called up, they are optimised to the maximum in terms of size and effectiveness.
Furthermore, there is a mini version for each list version, which only contains domains that can be found on the top 1M lists of the last 12 months.

I have already thought about a highly condensed anti-trackers list, but have not yet tackled the issue. Maintaining the current lists requires a lot of effort.

I don't use your lists yet, but if they provide added value for me, I will add them to the ultimate list first.

**Comment by spirillen** [comment]
@hagezi 

> I have already thought about a highly condensed anti-trackers list

That system is already up at @mypdns as my project do not whitelist any domains, which means tracking is tracking, no matter if it comes from github/microsoft or Google. Then the individual users may whitelist as they seems fit for their network, that is not and can never be my responsibility to let in known snoopers of anybody's network.

Everyone is most welcome to contribute.
