### ISSUE TITLE
Twitter / X login break

### ISSUE THREAD

**Issue by yokoffing** [Kees1958/W3C_annual_most_used_survey_blocklist#89]
`||twitter.com^$3p` breaks login to `x.com` using the **World's most used advertising and tracking networks** list.

 You're going to probably run into issues with `||google.com^$3p` too.

cc: https://github.com/yokoffing/filterlists/issues/144#issuecomment-2176925644

**Comment by Kees1958** [comment]
Hal,

Thanks for reporting, corrected now

**Google.com 3p rules**
||adservice.google.com^$third-party
||adwords.google.com^$third-party
||analytics.google.com^$third-party
||google.com/ads^$third-party
||google.com/adsense^$third-party
||google.com/pagead^$third-party
||adservice.google.com^$third-party

**Twitter.com 3p rules now**
||ads.twitter.com^$third-party
||ads-api.twitter.com^$third-party
||ads-twitter.com^$third-party
||analytics.twitter.com^$third-party
||platform.twitter.com^$third-party
||static.ads-twitter.com^$third-party

I will close this thank you very much
