### ISSUE TITLE
Ghostery suggestions

### ISSUE THREAD

**Issue by LexterS999** [Kees1958/W3C_annual_most_used_survey_blocklist#90]
Take a look at this instruction https://github.com/whotracksme/whotracks.me/blob/master/whotracksme/data/Readme.md

**Comment by Kees1958** [comment]
For what should I look :-)

**Comment by LexterS999** [comment]
For generating filter list data for your own repo. There is instruction how to use database of whotracks.me

**Comment by Kees1958** [comment]
> For generating filter list data for your own repo. There is instruction how to use database of whotracks.me

OK, Thanks.

I extracted their JSON and but it also contains trackers which need allow exception or specific domain limitations, which requires to much fiddling and tweaking (my world most used is 99,99% third-party only and has less than a handfull domain exceptions).
