### ISSUE TITLE
[Website breakage] railway.gov.tw 

### ISSUE THREAD

**Issue by haoltw** [Kees1958/W3C_annual_most_used_survey_blocklist#92]
Issue URL
https://www.railway.gov.tw/tra-tip-web/tip

Website broken when using EU_US_MV3_most_common_ad+tracking_networks.txt or World most used advertising and tracking networks.txt.
Please confirm and fix this issue.
Thank you.

**Comment by Kees1958** [comment]
Because of the last summer days in the Netherlands, I was off line all weekend. I think I have corrected it. Can't check now (takes some time for Github to publish updates to raw and I got to run now to catch a train). I will check this eveneing (Amsterdam time)

**Comment by haoltw** [comment]
EU_US_MV3_most_common_ad+tracking_networks.txt
>>I just confirmed that the problem has been fixed.
